
CONFIG_SHELL_PROMPT_UART="rt_super>"
CONFIG_SHELL_PROMPT_RTT=""

CONFIG_SHELL=y
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SHELL_BACKEND_RTT=y

CONFIG_LOG=y
CONFIG_THREAD_MONITOR=y
CONFIG_REBOOT=y

CONFIG_SHELL_LOG_FORMAT_TIMESTAMP=n
