/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name PDM_CLK01 (coord R1), U40[4]/U41[4]/PDM_CLK01_OnBoard
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_PDM_CLK01_PERIPHERAL DMIC0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_PDM_CLK01_SIGNAL CLK
/*!
 * @brief Signal channel */
#define BOARD_INITPINS_PDM_CLK01_CHANNEL 0_1
/* @} */

/*! @name PDM_CLK23 (coord U1), U19[D5]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_CLK23_PERIPHERAL DMIC0   /*!<@brief Peripheral name */
#define BOARD_INITPINS_PDM_CLK23_SIGNAL CLK         /*!<@brief Signal name */
#define BOARD_INITPINS_PDM_CLK23_CHANNEL 2_3        /*!<@brief Signal channel */
                                                    /* @} */

/*! @name PDM_CLK45 (coord R2), U19[E3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_CLK45_PERIPHERAL DMIC0   /*!<@brief Peripheral name */
#define BOARD_INITPINS_PDM_CLK45_SIGNAL CLK         /*!<@brief Signal name */
#define BOARD_INITPINS_PDM_CLK45_CHANNEL 4_5        /*!<@brief Signal channel */
                                                    /* @} */

/*! @name PDM_CLK67 (coord T2), U19[C2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_CLK67_PERIPHERAL DMIC0   /*!<@brief Peripheral name */
#define BOARD_INITPINS_PDM_CLK67_SIGNAL CLK         /*!<@brief Signal name */
#define BOARD_INITPINS_PDM_CLK67_CHANNEL 6_7        /*!<@brief Signal channel */
                                                    /* @} */

/*! @name PDM_DATA01 (coord U2), U40[1]/U41[1]/PDM_DATA01_OnBoard
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_PDM_DATA01_PERIPHERAL DMIC0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_PDM_DATA01_SIGNAL DATA
/*!
 * @brief Signal channel */
#define BOARD_INITPINS_PDM_DATA01_CHANNEL 0_1
/* @} */

/*! @name PDM_DATA23 (coord R3), J31[6]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_DATA23_PERIPHERAL DMIC0    /*!<@brief Peripheral name */
#define BOARD_INITPINS_PDM_DATA23_SIGNAL DATA         /*!<@brief Signal name */
#define BOARD_INITPINS_PDM_DATA23_CHANNEL 2_3         /*!<@brief Signal channel */
                                                      /* @} */

/*! @name PDM_DATA45 (coord P3), U19[E2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_DATA45_PERIPHERAL DMIC0    /*!<@brief Peripheral name */
#define BOARD_INITPINS_PDM_DATA45_SIGNAL DATA         /*!<@brief Signal name */
#define BOARD_INITPINS_PDM_DATA45_CHANNEL 4_5         /*!<@brief Signal channel */
                                                      /* @} */

/*! @name PDM_DATA67 (coord P5), U19[E1]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_DATA67_PERIPHERAL DMIC0    /*!<@brief Peripheral name */
#define BOARD_INITPINS_PDM_DATA67_SIGNAL DATA         /*!<@brief Signal name */
#define BOARD_INITPINS_PDM_DATA67_CHANNEL 6_7         /*!<@brief Signal channel */
                                                      /* @} */

/*! @name FC0_TXD_SCL_MISO_WS (coord G2), J16[1]/U27[3]/U9[12]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0         /*!<@brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
                                                                   /* @} */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord G4), JP21[2]/U28[3]/U9[13]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_UART_RXD_PERIPHERAL FLEXCOMM0           /*!<@brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                                     /* @} */

/*! @name I3C0_PUR (coord B6), J18[3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I3C0_PUR_PERIPHERAL I3C    /*!<@brief Peripheral name */
#define BOARD_INITPINS_I3C0_PUR_SIGNAL PUR        /*!<@brief Signal name */
                                                  /* @} */

/*! @name I3C0_SCL (coord N17), J18[1]/U8[2]/U17[A6]/SCL_CODEC
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I3C0_SCL_PERIPHERAL I3C                         /*!<@brief Peripheral name */
#define BOARD_INITPINS_I3C0_SCL_SIGNAL SCL                             /*!<@brief Signal name */
                                                                       /* @} */

/*! @name I3C0_SDA (coord P16), J18[2]/U8[3]/U17[B6]/SDA_CODEC
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_I3C0_SDA_PERIPHERAL I3C                         /*!<@brief Peripheral name */
#define BOARD_INITPINS_I3C0_SDA_SIGNAL SDA                             /*!<@brief Signal name */
                                                                       /* @} */

/*! @name FC2_SCK (coord A3), Q4[5]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LED_GREEN_PERIPHERAL FLEXCOMM2 /*!<@brief Peripheral name */
#define BOARD_INITPINS_LED_GREEN_SIGNAL SCK           /*!<@brief Signal name */
                                                      /* @} */

/*! @name HS_SPI_MISO (coord M2), U19[D2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LCD_MISO_PERIPHERAL FLEXCOMM14 /*!<@brief Peripheral name */
#define BOARD_INITPINS_LCD_MISO_SIGNAL MISO           /*!<@brief Signal name */
                                                      /* @} */

/*! @name HS_SPI_MOSI (coord N1), U19[C4]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LCD_MOSI_PERIPHERAL FLEXCOMM14              /*!<@brief Peripheral name */
#define BOARD_INITPINS_LCD_MOSI_SIGNAL MOSI                        /*!<@brief Signal name */
                                                                   /* @} */

/*! @name HS_SPI_SCK (coord L2), U19[D3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LCD_SCK_PERIPHERAL FLEXCOMM14 /*!<@brief Peripheral name */
#define BOARD_INITPINS_LCD_SCK_SIGNAL SCK            /*!<@brief Signal name */
                                                     /* @} */

/*! @name FC5_RXD_SDA_MOSI_DATA (coord J16), J28[4]/JP30[1]/J45[22]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_ACC_INT_PERIPHERAL FLEXCOMM5           /*!<@brief Peripheral name */
#define BOARD_INITPINS_ACC_INT_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                              /* @} */

/*! @name PIO2_5 (coord U13), LCD_CMD_DATA
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LCD_CMD_DATA_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_LCD_CMD_DATA_SIGNAL PIO2                        /*!<@brief Signal name */
#define BOARD_INITPINS_LCD_CMD_DATA_CHANNEL 5                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_CMD_DATA_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_CMD_DATA_GPIO_PIN_MASK (1U << 5U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LCD_CMD_DATA_PORT 2U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_CMD_DATA_PIN 5U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_CMD_DATA_PIN_MASK (1U << 5U)                /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name PIO2_6 (coord U15), LCD_RST
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LCD_RST_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_LCD_RST_SIGNAL PIO2                        /*!<@brief Signal name */
#define BOARD_INITPINS_LCD_RST_CHANNEL 6                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_RST_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_RST_GPIO_PIN_MASK (1U << 6U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LCD_RST_PORT 2U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_RST_PIN 6U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_RST_PIN_MASK (1U << 6U)                /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PIO2_7 (coord U16), LCD_BL
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LCD_BL_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_LCD_BL_SIGNAL PIO2                        /*!<@brief Signal name */
#define BOARD_INITPINS_LCD_BL_CHANNEL 7                          /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_BL_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_BL_GPIO_PIN_MASK (1U << 7U)           /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LCD_BL_PORT 2U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_BL_PIN 7U                             /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_BL_PIN_MASK (1U << 7U)                /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PIO1_14 (coord N2), SPI_SSEL
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_SPI_SSEL_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_SPI_SSEL_SIGNAL PIO1                        /*!<@brief Signal name */
#define BOARD_INITPINS_SPI_SSEL_CHANNEL 14                         /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SPI_SSEL_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SPI_SSEL_GPIO_PIN_MASK (1U << 14U)          /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SPI_SSEL_PORT 1U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_SSEL_PIN 14U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_SSEL_PIN_MASK (1U << 14U)               /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PIO0_26 (coord A2), TP5
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_TP5_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_TP5_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_TP5_CHANNEL 26                         /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TP5_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_TP5_GPIO_PIN_MASK (1U << 26U)          /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_TP5_PORT 0U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TP5_PIN 26U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_TP5_PIN_MASK (1U << 26U)               /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
