manifest:
  defaults:
    revision: main

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: ehughes
      url-base: https://github.com/ehughes


  defaults:
    remote: zephyrproject-rtos
    revision: main

  projects:

    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      revision: main
      import: true
    - name: egfx
      remote: ehughes
      repo-path: egfx
      revision: v2.0
     
      
  self:
    path: rt_super_z
    
