manifest:
  defaults:
    revision: main

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nordic
      url-base: https://github.com/krish2718

  defaults:
    remote: zephyrproject-rtos
    revision: main

  projects:
    - name: sdk-nrf
      path: nrf
      remote: nordic
      revision: ad912fcfdd0b82b75c75c09ea06feb32b664353f
      import: true
    - name: hal_nxp
      revision: 904830e8f684a9fd573751a1cdecde877ec49242
      path: modules/hal/nxp
      groups:
        - hal
  self:
    path: rt_super_z
    
