/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PSEDRAIN_EN 0x0400u    /*!<@brief Pseudo Output Drain is enabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC2_RXD_SDA_MOSI_DATA (coord D6), J36[8]/J47[7]/J48[15]/U109[64]/JS5[2]/FC2_SDA
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_FC2_SDA_PERIPHERAL FLEXCOMM2
/*!
 * @brief Signal name */
#define BOARD_INITPINS_FC2_SDA_SIGNAL RXD_SDA_MOSI_DATA
/* @} */

/*! @name FC2_SCK (coord A3), FC2_CLK
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_FC2_CLK_PERIPHERAL FLEXCOMM2 /*!<@brief Peripheral name */
#define BOARD_INITPINS_FC2_CLK_SIGNAL SCK           /*!<@brief Signal name */
                                                    /* @} */

/*! @name PIO0_19 (coord A1), GREEN_LED
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_GREEN_LED_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_GREEN_LED_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_GREEN_LED_CHANNEL 19                         /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GREEN_LED_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GREEN_LED_GPIO_PIN_MASK (1U << 19U)          /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_GREEN_LED_PORT 0U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GREEN_LED_PIN 19U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_GREEN_LED_PIN_MASK (1U << 19U)               /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PIO0_27 (coord B3), RED_LED
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_RED_LED_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_RED_LED_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_RED_LED_CHANNEL 27                         /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RED_LED_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RED_LED_GPIO_PIN_MASK (1U << 27U)          /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_RED_LED_PORT 0U                            /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RED_LED_PIN 27U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_RED_LED_PIN_MASK (1U << 27U)               /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PDM_CLK67 (coord T2), JP35[2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_QSPI_B_CS0_PERIPHERAL DMIC0   /*!<@brief Peripheral name */
#define BOARD_INITPINS_QSPI_B_CS0_SIGNAL CLK         /*!<@brief Signal name */
#define BOARD_INITPINS_QSPI_B_CS0_CHANNEL 6_7        /*!<@brief Signal channel */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
