/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord G4), JP21[2]/U28[3]/U9[13]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_UART_RXD_PERIPHERAL FLEXCOMM0           /*!<@brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                                     /* @} */

/*! @name FC0_TXD_SCL_MISO_WS (coord G2), J16[1]/U27[3]/U9[12]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0         /*!<@brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
                                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FLEXSPI0A_DATA0 (coord T5), U108[D3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ0_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ0_SIGNAL FLEXSPI_A_DATA0   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA1 (coord U5), U108[D2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ1_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ1_SIGNAL FLEXSPI_A_DATA1   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA2 (coord P6), U108[C4]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ2_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ2_SIGNAL FLEXSPI_A_DATA2   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA3 (coord P7), U108[D4]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ3_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ3_SIGNAL FLEXSPI_A_DATA3   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA4 (coord T7), U108[D5]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ4_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ4_SIGNAL FLEXSPI_A_DATA4   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA5 (coord U7), U108[E3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ5_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ5_SIGNAL FLEXSPI_A_DATA5   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA6 (coord R7), U108[E2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ6_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ6_SIGNAL FLEXSPI_A_DATA6   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DATA7 (coord T8), U108[E1]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ7_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_ADQ7_SIGNAL FLEXSPI_A_DATA7   /*!<@brief Signal name */
                                                                /* @} */

/*! @name FLEXSPI0A_DQS (coord U9), U108[C3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_DQS_PERIPHERAL FLEXSPI     /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_DQS_SIGNAL FLEXSPI_A_DQS   /*!<@brief Signal name */
                                                             /* @} */

/*! @name FLEXSPI0A_SCLK (coord T9), U108[B2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_CLK_PERIPHERAL FLEXSPI      /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_CLK_SIGNAL FLEXSPI_A_SCLK   /*!<@brief Signal name */
                                                              /* @} */

/*! @name FLEXSPI0A_SS0_N (coord T4), U108[A3]
  @{ */
/* Routed pin properties */
#define BOARD_INITPSRAMPINS_PSRAM_CE_PERIPHERAL FLEXSPI       /*!<@brief Peripheral name */
#define BOARD_INITPSRAMPINS_PSRAM_CE_SIGNAL FLEXSPI_A_SS0_B   /*!<@brief Signal name */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPsRamPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
