# nothing here
CONFIG_SPI=y

CONFIG_LOG=y

CONFIG_USE_SEGGER_RTT=y
CONFIG_CONSOLE=y
CONFIG_SHELL=y


#RTT Shell
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SHELL_BACKEND_RTT=y



CONFIG_SPI_LOG_LEVEL_DBG=y